Json = require("json")
Inspect = require("inspect")
local f = assert(io.open("test.json", "rb"))
local c = f:read("*all")
local txt = Json.decode(c)
print(Inspect(txt))
f:close()
f = assert(io.open("out.json", "w"))
local enc = Json.encode(txt)
f:write(enc)
f:close()
